// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtAxHyzRXxotOXl6QQd3hBBRomTa2KZ98',
    appId: '1:671663487251:web:17f401ef596347469082e6',
    messagingSenderId: '671663487251',
    projectId: 'moviesiiiauth',
    authDomain: 'moviesiiiauth.firebaseapp.com',
    storageBucket: 'moviesiiiauth.appspot.com',
    measurementId: 'G-YXCNF95617',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVw5UTU6dpQRZDTaZIacaSA73ec4zhEhw',
    appId: '1:671663487251:android:eeb5654b6daaa7659082e6',
    messagingSenderId: '671663487251',
    projectId: 'moviesiiiauth',
    storageBucket: 'moviesiiiauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu8jZrQ2ZupfhCuB-waNkyle7SjwgLjsw',
    appId: '1:671663487251:ios:05028e1272052e329082e6',
    messagingSenderId: '671663487251',
    projectId: 'moviesiiiauth',
    storageBucket: 'moviesiiiauth.appspot.com',
    iosBundleId: 'com.example.flutterExamenFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu8jZrQ2ZupfhCuB-waNkyle7SjwgLjsw',
    appId: '1:671663487251:ios:05028e1272052e329082e6',
    messagingSenderId: '671663487251',
    projectId: 'moviesiiiauth',
    storageBucket: 'moviesiiiauth.appspot.com',
    iosBundleId: 'com.example.flutterExamenFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtAxHyzRXxotOXl6QQd3hBBRomTa2KZ98',
    appId: '1:671663487251:web:ca14c22f28ad8a849082e6',
    messagingSenderId: '671663487251',
    projectId: 'moviesiiiauth',
    authDomain: 'moviesiiiauth.firebaseapp.com',
    storageBucket: 'moviesiiiauth.appspot.com',
    measurementId: 'G-9QXQPV5XF0',
  );
}
